server:
  port: 8080
spring:
  application:
    name: MultiTenant
  datasource:
    url: 'jdbc:mysql://localhost:3309'
    username: 'root'
    password: 'rootpassword'
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: city
          contentType: application/json
        greetings-out:
          destination: city
          contentType: application/json
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none